# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     script: echo "Hello, world"


- script: start sl.exe
  displayName: Run_SL_EXE

# - script: sl.exe analyze
#   displayName: Run_SL_analyze

- script: sl.exe auth --no-diagnostic --org "e6227101-08ff-45e9-ae2d-781369efbb50" --token "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTg4NTczMDAsImlzcyI6IlNoaWZ0TGVmdCIsIm9yZ0lEIjoiZTYyMjcxMDEtMDhmZi00NWU5LWFlMmQtNzgxMzY5ZWZiYjUwIiwidXNlcklEIjoiYjllZjBkMzQtYmYyMi00ZTJmLThiZDgtZDk0MzcwMzY0NTE1Iiwic2NvcGVzIjpbInNlYXRzOndyaXRlIiwiZXh0ZW5kZWQiLCJhcGk6djIiLCJ1cGxvYWRzOndyaXRlIiwibG9nOndyaXRlIiwicGlwZWxpbmVzdGF0dXM6cmVhZCIsIm1ldHJpY3M6d3JpdGUiLCJwb2xpY2llczpjdXN0b21lciIsInBvbGljaWVzOnJlYWQiXX0.RpyNO9nBnJlkd-nGcBUZf6qSC1qjbCnSdf9xHag9XwASHagyu7cIRohqDhP9bVQxxtfYRZtEHbh4L_I3icUfHQKQem1t7vH_aAENQSwIN6xyTZP6kZiDTxp9qhal_z2AhMotnYdwbYK5853ppuiTiFUa--krr_awt6WhFNJP045PXAe7ZfeDWLMIMc7oHGOscneq5lpFkPRZN4dqjK9ftdnYrkURD47T0sr9ZiN4hTg6dxAzKQv_QsOqjXjIe32MnNPoL7dAXrUonXDHaNf45FbAAJtotXGM3TTJz-28rwe_RwDVaOrMTg7c93_r5yo6QbdnKNX7ZRttpzejyt92OQ"
  displayName: Run_SL_auth
  
  
- script: sl.exe update csharp2cpg
  displayName: SL_update
  
  
#- script: sl.exe analyze --csharp --dotnet-core --wait --app Azure TestProject.sln
- script: sl.exe analyze --csharp --dotnet --wait --app Azure TestProject.sln
  displayName: Run_SL_analyze

- script: echo "Hello, world"
  displayName: Test1001
    
- script: echo %cd%
  displayName: Test1002

- script: dir
  displayName: Test1003
